name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  build-docker:
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.push.outputs.digest }}

    steps:
    - uses: actions/checkout@v4

    - uses: docker/setup-buildx-action@v3

    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build + push and grab the digest
    - id: push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: docker.io/exactlyprateek/verifier03:${{ github.sha }}
        outputs: type=registry        # exposes 'digest' output:contentReference[oaicite:1]{index=1}
